const OLD='etfDividendTrackerV1',KEY='etfDividendTrackerV2',BAK='etfDividendTrackerV1Backup';
let state={transactions:[],dividends:[]}, publicDividends=[];
const $=s=>document.querySelector(s),money=n=>'NT$ '+Math.round(n).toLocaleString('zh-TW'),fmt=s=>s?s.replaceAll('-','/'):'—';
function loadLocal(){if(!localStorage.getItem(KEY)){try{let raw=localStorage.getItem(OLD),o=JSON.parse(raw);if(o&&Array.isArray(o.holdings)){localStorage.setItem(BAK,raw);state={transactions:o.holdings.map((h,i)=>({id:'m'+i,ticker:String(h.ticker).toUpperCase(),date:h.buyDate,type:'buy',shares:+h.shares})),dividends:o.dividends||[]};localStorage.setItem(KEY,JSON.stringify(state))}}catch{}}try{let x=JSON.parse(localStorage.getItem(KEY));if(x)state=x}catch{}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function sign(t){return t.type==='sell'?-t.shares:t.shares}
function at(t,d='9999-12-31'){return state.transactions.filter(x=>x.ticker===t&&x.date<d).reduce((s,x)=>s+sign(x),0)}
function allDividends(){let map=new Map();[...(state.dividends||[]),...publicDividends].forEach(d=>{let k=[d.ticker,d.exDate,d.payDate].join('|');if(d.dividend!==null&&d.dividend!==undefined&&d.dividend!=='')map.set(k,{...d,dividend:+d.dividend})});return [...map.values()]}
function events(){return allDividends().map(d=>({...d,shares:at(d.ticker,d.exDate)})).filter(x=>x.shares>0&&Number.isFinite(+x.dividend)).map(x=>({...x,amount:x.shares*x.dividend})).sort((a,b)=>a.payDate.localeCompare(b.payDate))}
function render(){let ev=events(),today=new Date().toISOString().slice(0,10),f=ev.filter(x=>x.payDate>=today),p={};state.transactions.forEach(t=>p[t.ticker]=(p[t.ticker]||0)+sign(t));let active=Object.entries(p).filter(x=>x[1]>0),total=active.reduce((s,x)=>s+x[1],0);$('#count').textContent=active.length+' 檔';$('#totalShares').textContent=total.toLocaleString()+' 股';$('#future').textContent=money(f.reduce((s,x)=>s+x.amount,0));if(f.length){let d=f[0].payDate,a=f.filter(x=>x.payDate===d);$('#next').textContent=money(a.reduce((s,x)=>s+x.amount,0));$('#nextDetail').textContent=fmt(d)+' · '+[...new Set(a.map(x=>x.ticker))].join('、')}else{$('#next').textContent='—';$('#nextDetail').textContent='尚無待領資料'}let m={};f.forEach(x=>m[x.payDate.slice(0,7)]=(m[x.payDate.slice(0,7)]||0)+x.amount);$('#months').innerHTML=Object.keys(m).sort().map(k=>`<div class="card month"><span class="muted">${k.replace('-',' 年 ')} 月</span><b>${money(m[k])}</b></div>`).join('')||'<div class="card empty">目前沒有待領股息</div>';$('#schedule').innerHTML=f.map(x=>`<div class="row"><div><b>${x.ticker}</b><div class="muted">${x.name||''} · 除息 ${fmt(x.exDate)} · 入帳 ${fmt(x.payDate)} · ${x.shares.toLocaleString()} 股 × ${x.dividend}</div></div><b>${money(x.amount)}</b></div>`).join('')||'<div class="empty">目前沒有待領股息</div>';$('#portfolio').innerHTML=active.map(x=>`<div class="row"><b>${x[0]}</b><b>${x[1].toLocaleString()} 股</b></div>`).join('')+(active.length?`<div class="row"><b>全部 ETF 總計</b><b>${total.toLocaleString()} 股</b></div>`:'<div class="empty">目前沒有持股</div>');$('#holdings').innerHTML=state.transactions.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(t=>{let i=state.transactions.indexOf(t);return `<div class="row"><div><b>${t.ticker}</b> · ${t.type==='buy'?'買進':'賣出'}<div class="muted">${fmt(t.date)} · ${t.shares.toLocaleString()} 股</div></div><button class="secondary" data-t="${i}">刪除</button></div>`}).join('')||'<div class="empty">尚無交易紀錄</div>';$('#dividends').innerHTML=allDividends().filter(d=>at(d.ticker)>0).sort((a,b)=>b.exDate.localeCompare(a.exDate)).slice(0,50).map(d=>`<div class="row"><div><b>${d.ticker}</b><div class="muted">${d.name||''} · 除息 ${fmt(d.exDate)} · 發放 ${fmt(d.payDate)} · 每股 ${d.dividend} 元</div></div></div>`).join('')||'<div class="empty">尚無持有 ETF 的配息資料</div>';document.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{state.transactions.splice(+b.dataset.t,1);save()})}
async function syncPublic(){let s=$('#syncStatus');try{let r=await fetch('./data/dividends.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error();let x=await r.json();publicDividends=Array.isArray(x.items)?x.items:[];s.textContent=`已更新：${x.updatedAt||'未知'} · ${publicDividends.length.toLocaleString()} 筆公開配息`;render()}catch{publicDividends=[];s.textContent='目前無法取得公開配息資料，可稍後重新整理';render()}}
$('#form').onsubmit=e=>{e.preventDefault();let ticker=$('#ticker').value.trim().toUpperCase(),date=$('#tradeDate').value,type=$('#tradeType').value,shares=Math.floor(+$('#shares').value);if(!ticker||!date||shares<1)return;if(type==='sell'&&at(ticker,date)<shares){$('#msg').textContent='賣出股數超過當時持股';return}state.transactions.push({id:Date.now(),ticker,date,type,shares});save();e.target.reset()};
$('#clear').onclick=()=>{if(confirm('確定清除交易資料？V1 備份仍保留。')){state={transactions:[],dividends:[]};save()}};
$('#export').onclick=()=>{let a=document.createElement('a'),b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});a.href=URL.createObjectURL(b);a.download='ETF股息追蹤器_V3備份.json';a.click()};
$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{try{let x=JSON.parse(await e.target.files[0].text());if(x.transactions)state=x;else if(x.holdings)state={transactions:x.holdings.map((h,i)=>({id:'i'+i,ticker:h.ticker,date:h.buyDate,type:'buy',shares:+h.shares})),dividends:x.dividends||[]};save();alert('匯入完成')}catch{alert('格式不正確')}};
$('#refreshData').onclick=syncPublic;
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(r=>r.update());navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload())}
loadLocal();render();syncPublic();
