const KEY='etfDividendTrackerV1'; let state={holdings:[],dividends:[]};
const $=s=>document.querySelector(s), money=n=>'NT$ '+Math.round(n).toLocaleString('zh-TW'), fmt=s=>s? s.replaceAll('-','/'):'—';
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&Array.isArray(x.holdings)&&Array.isArray(x.dividends))state=x}catch{} render()}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function events(){let out=[];for(const h of state.holdings)for(const d of state.dividends)if(h.ticker===d.ticker&&h.buyDate<d.exDate)out.push({...d,shares:h.shares,amount:h.shares*d.dividend});return out.sort((a,b)=>a.payDate.localeCompare(b.payDate))}
function render(){const ev=events(), today=new Date().toISOString().slice(0,10), fut=ev.filter(e=>e.payDate>=today);$('#count').textContent=new Set(state.holdings.map(h=>h.ticker)).size+' 檔';$('#future').textContent=money(fut.reduce((s,e)=>s+e.amount,0));if(fut.length){let date=fut[0].payDate, same=fut.filter(e=>e.payDate===date);$('#next').textContent=money(same.reduce((s,e)=>s+e.amount,0));$('#nextDetail').textContent=fmt(date)+' · '+[...new Set(same.map(e=>e.ticker))].join('、')}else{$('#next').textContent='—';$('#nextDetail').textContent='尚無待領資料'}let m={};fut.forEach(e=>m[e.payDate.slice(0,7)]=(m[e.payDate.slice(0,7)]||0)+e.amount);$('#months').innerHTML=Object.keys(m).sort().map(k=>`<div class="card month"><span class="muted">${k.replace('-',' 年 ')} 月</span><b>${money(m[k])}</b></div>`).join('')||'<div class="card empty">目前沒有待領股息</div>';$('#schedule').innerHTML=fut.map(e=>`<div class="row"><div><span class="ticker">${e.ticker}</span><div class="muted">除息 ${fmt(e.exDate)} · 入帳 ${fmt(e.payDate)} · ${e.shares.toLocaleString()} 股 × ${e.dividend}</div></div><span class="amount">${money(e.amount)}</span></div>`).join('')||'<div class="empty">目前沒有待領股息</div>';$('#holdings').innerHTML=state.holdings.map((h,i)=>`<div class="row"><div><span class="ticker">${h.ticker}</span><div class="muted">${h.shares.toLocaleString()} 股 · ${fmt(h.buyDate)}</div></div><button class="secondary" data-h="${i}">刪除</button></div>`).join('')||'<div class="empty">尚未加入持股</div>';$('#dividends').innerHTML=state.dividends.slice().sort((a,b)=>b.exDate.localeCompare(a.exDate)).map((d,i)=>`<div class="row"><div><span class="ticker">${d.ticker}</span><div class="muted">除息 ${fmt(d.exDate)} · 發放 ${fmt(d.payDate)} · 每股 ${d.dividend} 元</div></div><button class="secondary" data-d="${state.dividends.indexOf(d)}">刪除</button></div>`).join('')||'<div class="empty">尚未加入配息公告</div>';document.querySelectorAll('[data-h]').forEach(b=>b.onclick=()=>{state.holdings.splice(+b.dataset.h,1);save()});document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{state.dividends.splice(+b.dataset.d,1);save()})}
$('#form').onsubmit=e=>{e.preventDefault();let ticker=$('#ticker').value.trim().toUpperCase(),buyDate=$('#buyDate').value,shares=Math.floor(Number($('#shares').value));if(!ticker||!buyDate||shares<1)return;state.holdings.push({ticker,buyDate,shares});save();e.target.reset();$('#msg').textContent=`已加入 ${ticker} ${shares.toLocaleString()} 股`};
$('#divForm').onsubmit=e=>{e.preventDefault();let ticker=$('#divTicker').value.trim().toUpperCase(),exDate=$('#exDate').value,payDate=$('#payDate').value,dividend=Number($('#dividend').value);if(!ticker||!exDate||!payDate||dividend<0)return;state.dividends.push({ticker,exDate,payDate,dividend});save();e.target.reset()};
$('#clear').onclick=()=>{if(confirm('確定清除所有持股與配息資料？')){state={holdings:[],dividends:[]};save()}};
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ETF股息追蹤器備份.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const x=JSON.parse(await f.text());if(!Array.isArray(x.holdings)||!Array.isArray(x.dividends))throw 0;state=x;save();alert('備份匯入完成')}catch{alert('備份檔格式不正確')}e.target.value=''};
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#install').hidden=false});$('#install').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;$('#install').hidden=true}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');load();
